# Template Kubernetes Deployment Configuration
# This file contains all necessary Kubernetes resources

apiVersion: v1
kind: ConfigMap
metadata:
  name: template-example-app-config
  namespace: default
data:
  config.toml: |
    [app]
    app_name = "Template Example App"
    app_version = "0.2.0"
    environment = "production"
    
    [server]
    host = "0.0.0.0"
    port = 8080
    
    [database]
    host = "postgres-service"
    port = 5432
    database = "myapp"
    username = "postgres"
    password = "password"
    
    [redis]
    url = "redis://redis-service:6379"
    
    [logging]
    level = "info"
    format = "json"
    targets = ["stdout"]
    
    [monitoring]
    health_check_path = "/health"
    metrics_path = "/metrics"

---
apiVersion: v1
kind: Secret
metadata:
  name: template-example-app-secrets
  namespace: default
type: Opaque
data:
  database-password: cGFzc3dvcmQ=
  jwt-secret: eW91ci1zZWNyZXQta2V5LWhlcmU=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-example-app-deployment
  namespace: default
  labels:
    app: template-example-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: template-example-app
  template:
    metadata:
      labels:
        app: template-example-app
    spec:
      containers:
      - name: template-example-app
        image: template-example-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: template-example-app-secrets
              key: database-password
        - name: SECURITY_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: template-example-app-secrets
              key: jwt-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: template-example-app-service
  namespace: default
spec:
  selector:
    app: template-example-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: template-example-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: template-example-app-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
