[package]
name = "nested-example"
version = "0.2.0"
edition = "2021"

[dependencies]
quantum_config = { path = "../../" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"