# Web Server 配置文件
# 这是一个完整的 Web 服务器配置示例

[server]
# 服务器监听地址
host = "0.0.0.0"
# 服务器监听端口
port = 3000
# 工作线程数 (0 表示自动检测)
workers = 0
# 请求超时时间（秒）
timeout = 30
# 最大请求体大小（MB）
max_body_size = 16

[tls]
# 启用 TLS/HTTPS
enabled = false
# TLS 证书文件路径
# cert_file = "/path/to/cert.pem"
# TLS 私钥文件路径
# key_file = "/path/to/key.pem"
# 最小 TLS 版本
min_version = "1.2"

[cors]
# 启用 CORS
enabled = true
# 允许的源 (逗号分隔)
allowed_origins = "*"
# 允许的 HTTP 方法 (逗号分隔)
allowed_methods = "GET,POST,PUT,DELETE,OPTIONS"
# 允许的请求头 (逗号分隔)
allowed_headers = "*"
# 预检请求缓存时间（秒）
max_age = 3600

[logging]
# 日志级别 (trace, debug, info, warn, error)
level = "info"
# 日志格式 (json, pretty)
format = "pretty"
# 启用 HTTP 访问日志
access_log = true
# 日志文件路径 (留空表示输出到控制台)
# file = "/var/log/web_server.log"

[api]
# API 版本
version = "v1"
# API 路径前缀
prefix = "/api"
# 启用 API 文档端点
docs_enabled = true
# 速率限制（每分钟请求数，0 表示无限制）
rate_limit = 100