# Basic Example 配置文件
# 这是一个示例配置文件，展示了如何配置 basic_example 应用程序

# 应用程序名称
name = "Basic Example"

# 服务器主机地址
host = "localhost"

# 服务器端口
port = 8080

# 启用调试模式
debug = false

# 日志级别 (trace, debug, info, warn, error)
log_level = "info"

# 工作线程数
workers = 4