name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Show commit and toolchain info
      run: |
        echo "HEAD SHA:" && git rev-parse HEAD
        echo "Recent commits:" && git log --oneline -n 3 || true
        echo "rustc version:" && rustc -Vv
        echo "cargo version:" && cargo -Vv
        echo "Grep for problematic type aliases (should find none):"
        grep -Rn "pub type QuantumConfigEnvProvider" src || true
        grep -Rn "pub type QuantumConfigFileProviderGeneric" src || true
    - name: Clean
      run: cargo clean
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
